version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - npm install serverless
      - npm install serverless-wsgi serverless-python-requirements
      - ls
      - cd flaskapp
      - ls
      - serverless deploy
artifacts:
  files:
    - packaged-template.yml
