version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - npm install -g serverless
  build:
    commands:
      - cd flaskapp
      - sls deploy
artifacts:
  files:
    - packaged-template.yml
