version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - cd flaskapp
      - npm install serverless
      - npm install serverless-wsgi serverless-python-requirements
      - "ls -lart node_modules"
      - sudo node_modules/serverless deploy
artifacts:
  files:
    - packaged-template.yml
