version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - npm install serverless
      - npm install serverless-wsgi serverless-python-requirements
  build:
    commands:
      - cd flaskapp
      - which sls
      - which serverless
      - serverless deploy
artifacts:
  files:
    - packaged-template.yml
