AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  IAM User Manager

Globals:
  Function:
    Timeout: 3

Metadata:
  AWS::ServerlessRepo::Application:
    Name: iam-user-manager
    Description: Serverless App to manage AWS IAM users
    Author: abhijeetdeshkar

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  ApiFunction: # Adds a GET api endpoint at "/" to the ApiGatewayApi via an Api event
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'HELLO WORLD!', 'statusCode': 200}
#Resources:
#  IAMUserManager:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: flask-app/
#      Handler: app.app
#      Runtime: python3.6
#      Events:
#        HelloWorld:
#          Type: Api
#          Properties:
#            Path: /
#            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ListUsersApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/list-iam-users"
  IAMUserManager:
    Description: "IAMUserManager Lambda Function ARN"
    Value: !GetAtt IAMUserManager.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for IAMUserManager function"
    Value: !GetAtt IAMUserManagerRole.Arn
